name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create Build Directory and Copy Files
        run: |
          mkdir -p build/config
          mkdir -p ./config
          cp -r index.html styles.css js assets build/
          cp script.js build/

      - name: Create Firebase Config
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        run: |
          echo "Creating Firebase config file..."
          cat > ./config/firebase-config.js << EOF
          {
            "apiKey": "$FIREBASE_API_KEY",
            "authDomain": "$FIREBASE_AUTH_DOMAIN",
            "projectId": "$FIREBASE_PROJECT_ID",
            "storageBucket": "$FIREBASE_STORAGE_BUCKET",
            "messagingSenderId": "$FIREBASE_MESSAGING_SENDER_ID",
            "appId": "$FIREBASE_APP_ID",
            "measurementId": "$FIREBASE_MEASUREMENT_ID"
          }
          EOF
          echo "Firebase config file created at build/config/firebase-config.js"
          cat ./config/firebase-config.js
          cp ./config/firebase-config.js ./build/config/firebase-config.js
          ls -la ./config/
          ls -la
 
      - name : Updload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: build

      - name : Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: build-pages

      - name: Display structure of downloaded files
        run: ls -R;

      - name: Deploy GitHub Pages site
        # uses: peaceiris/actions-gh-pages@v3.9.3
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ github.token }} 
          

      # - name: Deploy to GitHub Pages
      #   uses: JamesIves/github-pages-deploy-action@v4.4.3
      #   with:
      #     branch: gh-pages
      #     folder: github-pages
      #     clean: true
      #     clean-exclude: |
      #       .nojekyll
      #       CNAME
